apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: hrh-cloud
  name: web-hrh-cloud-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  labels:
    app: hrh
spec:
  tls:
    - hosts:
        - hrh.michaelilyin.ru
      secretName: web-tls
  rules:
    - host: hrh.michaelilyin.ru
      http:
        paths:
          - path: /($|.*)
            backend:
              serviceName: web
              servicePort: 4000


---


#####
# Web Service
#####
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hrh-cloud
  labels:
    app: web
  name: web
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
  template:
    metadata:
      namespace: hrh-cloud
      labels:
        app: web
    spec:
      containers:
      - image: michaelilyin/hrh-web:latest
        imagePullPolicy: Always
        name: hrh-cloud-web
        env:
          - name: API
            value: "api.hrh.michaelilyin.ru"
          - name: AUTH_HOST
            value: "auth.michaelilyin.ru"
          - name: AUTH_PATH
            value: "https://auth.michaelilyin.ru/auth/realms/kiss-cloud"
          - name: AUTH_LOGIN_REDIRECT
            value: "https://hrh.michaelilyin.ru"
---
apiVersion: v1
kind: Service
metadata:
  namespace: hrh-cloud
  labels:
    app: web
  name: web
spec:
  ports:
  - name: 4000-4000
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: web
  type: ClusterIP

