apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: hrh-cloud
  name: hrh-cloud-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1$2$3
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  labels:
    app: hrh
spec:
  tls:
    - hosts:
        - hrh.michaelilyin.ru
      secretName: cl-tls
  rules:
    - host: hrh.michaelilyin.ru
      http:
        paths:
          - path: /(!api)(/|$)(.*)
            backend:
              serviceName: web
              servicePort: 80


---


#####
# Web Service
#####
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hrh-cloud
  labels:
    app: web
  name: web
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
  template:
    metadata:
      namespace: hrh-cloud
      labels:
        app: web
    spec:
      containers:
      - image: michaelilyin/hrh-web:latest
        imagePullPolicy: Always
        name: hrh-cloud-web
---
apiVersion: v1
kind: Service
metadata:
  namespace: hrh-cloud
  labels:
    app: web
  name: web
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  type: ClusterIP

